# Generated by Django 5.1.1 on 2025-01-10 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0003_finesrecord_paid_fine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finesaccidents',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finess', to='logsApp.registredcars'),
        ),
    ]
