# Generated by Django 5.1.1 on 2025-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0004_alter_finesaccidents_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finesrecord',
            name='paid_fine_image',
            field=models.FileField(blank=True, null=True, upload_to='paid_fines/'),
        ),
    ]
