# Generated by Django 5.1.1 on 2025-01-11 04:33

import django.db.models.deletion
import logsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0005_alter_finesrecord_paid_fine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensefile',
            name='fines_accident',
        ),
        migrations.RemoveField(
            model_name='finesaccidentsimage',
            name='fines_accident',
        ),
        migrations.AlterField(
            model_name='finesrecord',
            name='paid_fine_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='paid_fines/'),
        ),
        migrations.CreateModel(
            name='AccidentsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('fixin_date', models.DateField(blank=True, null=True)),
                ('report_pdf_file', models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.fines_accident_pdf_upload_to)),
                ('car_paperwork_file', models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.fines_accident_pdf_upload_to)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='logsApp.registredcars')),
                ('employees', models.ManyToManyField(blank=True, to='logsApp.employesinfo')),
            ],
        ),
        migrations.AddField(
            model_name='finesaccidentsimage',
            name='accidents_record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logsApp.accidentsrecord'),
        ),
        migrations.AddField(
            model_name='licensefile',
            name='accidents_record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='license_files', to='logsApp.accidentsrecord'),
        ),
        migrations.DeleteModel(
            name='FinesAccidents',
        ),
    ]
