# Generated by Django 5.1.2 on 2025-01-12 12:15

import logsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0006_remove_licensefile_fines_accident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finesrecord',
            name='paid_fine_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=logsApp.models.paid_fine_image_upload_to),
        ),
    ]
